### ISSUE TITLE
Presentation labels not configurable

### ISSUE THREAD

**Issue by roxana-muresan** [pivotal/monitoring-indicator-protocol#7]
I am using a custom presentation to monitor some application speciffic data. For that I am grouping two complementary data sets into one presentation. (A similar example would be to show the number of GET and POST requests in the same presentation as grouped). I could not find a way of setting the labels of the presentation (for example GET for red and POST for blue).       
I tried following settings without success (method will be GET or POST):
spec/[indicator]/
presentation:
        units: "counts"    
        labels: [method]
presentation:
        units: "counts"    
        labels:
        - method

Also the OOB presentation labels are showing wrong texts: HTTP Request Count (per minute) and HTTP Request Latency in milliseconds show as labels "web" and "{source_id='the source_id hexa string here'}"

I am using App Metrics 2.0.1-build.9

**Comment by iplay88keys** [comment]
@roxana-muresan Hi! We are going to update our docs accordingly, but we only support a subset of the Indicator Protocol schema in App Metrics:

```
spec:
  product:
    name: <name>
    version: <version>
  indicators:
    - name: <name>
      promql: <promql>
      presentation:
        chartType: <chartType>
        units: <units>
      documentation:
        title: <title>
        description: <description>
        recommendedMeasurement: <recommendedMeasurement>
        recommendedResponse: <recommendedResponse>
```
